services:
  nginx:
    image: nginx:1.21
    container_name: nginx_counter_web_app
    ports:
      - "8080:80"
    networks:
      - counter-app-network
    volumes:
      - ./app:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    build: ./php
    container_name: php_counter_web_app
    volumes:
      - ./app:/usr/src/app
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=counter_web_app
    networks:
      - counter-app-network
    env_file:
      - .env
  node:
    build: ./node
    container_name: node_counter_web_app
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - ./app:/usr/src/app
networks:
  counter-app-network:
    driver: bridge